version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    env_file:
      - .env
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./globals.sql:/docker-entrypoint-initdb.d/1-globals.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/2-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/3-data.sql
      - ./pgdata:/var/lib/postgresql/data/
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5440:5432
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5480
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5480:5480
    networks:
      - postgres-network

  redis:
    image: redis
    container_name: redis-1
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - postgres-network

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    container_name: pgbackup
    restart: always
    user: postgres:postgres
    volumes:
        - ./pgbackup:/backups
    links:
        - postgres
    depends_on:
        - postgres
    environment:
        - POSTGRES_HOST=host.docker.internal
        - POSTGRES_PORT=5440
        - POSTGRES_DB=vli
        - POSTGRES_USER=db_admin
        - POSTGRES_PASSWORD=db_admin
        - POSTGRES_EXTRA_OPTS=-Z9 --blobs
        - SCHEDULE=@daily
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8080

volumes:
  pgdata:
  db-data:
  pgadmin-data:
    
networks:
  postgres-network:
    driver: bridge