version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    env_file:
     - .env
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./globals.sql:/docker-entrypoint-initdb.d/1-globals.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/2-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/3-data.sql
      - ./pgdata:/var/lib/postgresql/data/
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5440:5432
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5480
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5480:5480
    networks:
      - postgres-network

volumes:
  pgdata:
  db-data:
  pgadmin-data:
networks:
  postgres-network:
    driver: bridge